/*
 * Copyright (c) Huawei Technologies Co., Ltd. 2020-2020. All rights reserved.
 * Generated by the CloudDB ObjectType compiler. DO NOT EDIT!
 */

class objectType1 {
    constructor() {
        this.bookName = undefined;
        this.author = undefined;
        this.id = undefined;
        this.publishTime = undefined;
        this.field5 = undefined;
        this.field6 = undefined;
    }

    setBookName(bookName) {
        this.bookName = bookName;
    }

    getBookName() {
        return this.bookName;
    }

    setAuthor(author) {
        this.author = author;
    }

    getAuthor() {
        return this.author;
    }

    setId(id) {
        this.id = id;
    }

    getId() {
        return this.id;
    }

    setPublishTime(publishTime) {
        this.publishTime = publishTime;
    }

    getPublishTime() {
        return this.publishTime;
    }

    setField5(field5) {
        this.field5 = field5;
    }

    getField5() {
        return this.field5;
    }

    setField6(field6) {
        this.field6 = field6;
    }

    getField6() {
        return this.field6;
    }
}

objectType1.className = 'objectType1';

export {objectType1}